### PR TITLE
Fixes error "Can't set timers inside simulations"

### PR DESCRIPTION
**Pull request by Kurounin**
Fixes errors caused by actions performed on collection documents, in client side methods. Will fix https://github.com/Kurounin/Pagination/issues/3

### CODE REVIEW

**Comment by dw72** [comment]
+1

**Comment by tcastelli** [comment]
+1

**Comment by jimmiebtlr** [comment]
+1

Not sure if it matters, but should the Meteor.clearTimeout right below it also be changed to clearTimeout?

**Comment by Kurounin** [comment]
Meteor.clearTimeout is just calling clearTimeout method, so it can be left as it is.

**Comment by ccorcos** [comment]
Hey sorry for the delay -- I haven't used meteor in almost a year now
(feathersjs is pretty dope!). I think a better solution might be to check
if Meteor.isClient before you unsubscribe. Or am I barking up the wrong
tree?

**Comment by jimmiebtlr** [comment]
So fork?  @Kurounin 

Sorry to hear it @ccorcos, I think I would miss the packages that can handle client and server most.  I imagine thing's like edgee:slingshot have considerably more boilerplate for a more pure node framework.  

What do you think the main advantage of feature.js is over meteor?

**Comment by ccorcos** [comment]
You're welcome to fork. Or I can add you as a collaborator so you can handle PR's and publishing new releases.

> I think I would miss the packages that can handle client and server most.

You still get this with npm + webpack. For example, in node.js you use `socketio = require('socketio')` and on the client, you use `socketio = require('socketio/client')`. Works fine for me. At the end of the day, Meteor is just way to opinionated for anything to be long-lived. I hate how you're stuck with their entire authentication stack. And Node fibers are old at this point.

> What do you think the main advantage of feature.js is over meteor?

(1) compatability (npm, any express middleware, Auth0, passport, sequelize, mongoose, circleci, testing, mocha, karma, nodeunit, webpack, hot module replacement, vantage, now.sh... pretty much anything Node-related). This goes hand in hand with being far less opinionated.

(2) scalability -- easily broken into microservices, and has a much more simple and sane methodology for real-time messages (similar to ccorcos:any-db) that works with *any database* or storage mechanism.

**Comment by jimmiebtlr** [comment]
Published to

https://atmospherejs.com/jimmiebtlr/subs-cache

with fix for the same bug.

**Pull request closed without merging**
