### PR TITLE
Count the number of computations that have called a subscription so we don't release it too early

### PR DESCRIPTION
**Pull request by veered**

### CODE REVIEW

**Comment by ccorcos** [comment]
nice find!

**Comment by BudgieInWA** [comment]
This solution is flawed. The decrementing needs to happen at the *intent* to stop, not when SubsCache would stop it. This is because SubsCache already discards some intents to stop. For example:

1. Sub is created, incrementing the count.
1. Sub is `stop`ped, causing the timeout to start.
1. Sub is created again. SubsCache combines it with the cached sub, clearing the timeout and incrementing the timeout again.
1. Sub is `stop`ped, causing the timeout to start.
1. Timeout expires, causing `stopNow` to be called, decrementing the count. The count is still one, and the underlying sub is not stopped.

I will submit our solution, (that we developed before seeing this) shortly.

**Comment by ccorcos** [comment]
6. the second timeout expires, calling stopNow, decrementing the counter, and finally stopping the sub

**Comment by BudgieInWA** [comment]
My understanding is

(3) first time out is cleared in `restart`, and thus never expires  
...  
(5) second timeout expires ...

**Comment by ccorcos** [comment]
fair point

**Pull request merged**
