### PR TITLE
Fix combined subs stopping early bug

### LINKED ISSUE #13: When subs are combined, the combined sub stops when the first sub is stopped, not the last
Consider a page with two independent sections (A and B) that both make a subscription with the same arguments. 

1. A loads and creates subscription `a`.
1. B loads and creates subscription `b` (which SubsCache combines with `a`).
1. A unloads, stopping `a`.

**Observed**: at this point, the SubsCache subscription is `delayedStop`ed. After the timeout, the real subscription is stopped, clearing the data that B is using.

**Expected**: the subscription is not stopped until `b` is stopped.

### PR DESCRIPTION
**Pull request by BudgieInWA**
Add reference counting to cached subs so that a sub is not stopped until all uses of the sub are done. The count is incremented on the intent to start (in `start`) and decremented on the intent to stop (in `stop`).

This has the same goal as #11, and is incompatible with it. (We didn't see it while developing this.) I think #11 is flawed, so I've submitted this PR to show our solution.

Closes #13

### CODE REVIEW

**Comment by paranoico** [comment]
Hello guys, I am retaking this packages maintenance.

Are your changes still valid? And we have a conflict.

Thanks for your answer.

**Comment by paranoico** [comment]
@BudgieInWA @Miges 

Guys, can you give me some input about your request? Is it still necessary?

**Comment by BudgieInWA** [comment]
Last time I checked, master was still flawed in the way [I described in #11](https://github.com/ccorcos/meteor-subs-cache/pull/11#issuecomment-176628278). I haven't been following the changes here recently, so I'm not sure if the problem has been addressed or not.

**Comment by paranoico** [comment]
Thanks @BudgieInWA , I will check it out.

**Pull request closed without merging**
