### PR TITLE
Re-run subscription on args changed to support changing subscription parameters

### PR DESCRIPTION
**Pull request by jankapunkt**
Basically added a check, whether the function is called with different arguments and if so, runs through as like a first call and basically updates the sub.

There are also some tests provided. Please not, that there is some untested code remaining (such as hooks). There is more test support requirement to gain a good test coverage.

**Please test well, before merging this PR.**

### CODE REVIEW

**Comment by nicooprat** [comment]
Any plan to merge this? Thanks!

**Comment by paranoico** [comment]
We cannot test this throughout full enough to merge.
@nicooprat could you support it?

**Comment by nicooprat** [comment]
First tests are successful! 

But it looks like, when changing the subscription params, its `ready()` returns false once even if datas are already available, then immediately returns true. For example, when going back to the previous page if datas are still available in cache. An optimisation would be to check this before running 2 times for nothing (potentially).

Thanks!

**Comment by paranoico** [comment]
Thanks to you @nicooprat 
I will merge it now then.

**Comment by nicooprat** [comment]
I guess it would be great to make some more tests before publishing the package don’t you think? Any idea to avoid the issue I talked about? 

Thanks :)

**Comment by paranoico** [comment]
Publishing the package is still on hold until we are sure there is no more issues.
We have some on Cordova using JS version, if you have more spare time fill free to post a PR fixing the issue, in matter of fact, on my side we are very busy with a planned delivery for more than 100 android phones.
Anyway, from my view the issue you detected is not too big, so I merged for now.
Of course if we have some time in near future we can investigate the issue.
Thanks to you.

**Comment by jankapunkt** [comment]
@nicooprat @paranoico  If I have time in the next week I will check it out and try to improve it.

**Comment by paranoico** [comment]
Thanks a lot @jankapunkt 
We are also to try to find a bug and fix it in following days.

**Comment by nicooprat** [comment]
Just saw that cache hashes have "doubled" quotes, like this:

capture d ecran 2017-11-04 a 20 51 33

Seems to work anyway...

**Comment by paranoico** [comment]
Wow, did not notice that.

**Pull request merged**
